### ISSUE TITLE
negative widths and heights for rectangles requested from backend

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#11]
I took a look at the Rust code for (mod.rs) EntityUpdate and in the match block for "ChangeShape(specific_shape) => {", I don't see any code to ensure positive values (though I don't have full traction on the syntax yet).  Not sure if this is playing into the other issue with mismatched height or not.

**Comment by Jragonmiris** [comment]
You were right, but actually looking for `AlterRect`/`AlterTriangle`. `ChangeShape` is the one that lets you change it from a rectangle to a triangle or vice versa.
