### ISSUE TITLE
Realtime visualization is broken

### ISSUE THREAD

**Issue by LinearZoetrope** [SCAII/SCAII#116]
@jedirv 

It looks like the current version of `viz` only supports replays. I was attempting to debug a non-terminating game (hence I couldn't record a replay), and was trying to use the `viz_example` to show it on the webpage, but got a lot of crashes because it wasn't getting components like replay steps.

The bug would've been really easy to fix if I could have seen it (it only happened when attacking friendly units), but unfortunately it took me a couple hours of headscratching :/.

I'm not sure this is top priority, especially because I don't know how complex the fix is, but it is something I'd really like to see if possible to help me get some of this stuff done.

**Comment by jedirv** [comment]
dofcff5 partially fixes live viz.  Game plays but entity shape lists are empty.  Passing back to Zoe.
