### ISSUE TITLE
Add closure library

### ISSUE THREAD

**Issue by Jragonmiris** [SCAII/SCAII#12]
@jedirv I can't run your programs because the library isn't found. Then I recalled that we said we weren't going to commit the library because it was large.

I think we should do that so we can collaborate more easily. I'd store it under a folder called "vendor" since we're vendoring the closure library. Something like `SCAII/vendor/js`.

**Comment by jedirv** [comment]
Woops - forgot about that - I'm hesitant to add it, but will if you green light it after seeing these numbers - it's 2646 files at 126M.  (I recall cursing myself after doing this in a prior project - but those were bigger image files - perhaps it was the size vs file count that dominated the pain experience).

The alternative would be to do:

git clone in the https://github.com/google/closure-library.git

in the viz\js dir to get it working with the way I have things laid out at the moment. 

I'll pass this enhancement to you and if you want me to add it in, pass back to me and I will make it so.

**Comment by Jragonmiris** [comment]
There are two ways to go here:

1. Use git submodules. These mean you don't automatically download them whenever you clone the repository, BUT it does mean you have to remember to do `git submodule init` whenever you want to work with the Viz stuff.

2. Just vendor it straight in the root like I mentioned.

I prefer vendoring to submodules because submodules are really unwieldy to work with and there's that extra step of remembering to do the submod init and reminding all future contributors to do it, but realistically we can do either.

**Comment by Jragonmiris** [comment]
Third option: use npm

https://www.npmjs.com/package/google-closure-library

**Comment by Jragonmiris** [comment]
There's also using `npm` to install it and requiring that. I think while npm requires node, it doesn't mean we have to use node in our project.

https://www.npmjs.com/package/google-closure-compiler

**Comment by Jragonmiris** [comment]
Nevermind, I tried it. It has the same problems as the git clone.

**Comment by Jragonmiris** [comment]
Closing in favor of #19 this is a little more work but it will handle it for us.
