### ISSUE TITLE
action naming adjustments

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#126]
Let's do this to hedge against design waffling:

- add a field to BarGourp for action (will always be "attack" for now)
- add a field to BarGroup for quadrant_name  ("Q1", :Q2", etc)
- change name  field to "target_name" ("enemy town", "enemy tank", etc);

That way I can construct labels via action+quadrant_name or action+target_name depending on the need.

**Comment by LinearZoetrope** [comment]
There's no way to fetch the target info at the moment, so quadrants is all we got, which is implemented.
