### ISSUE TITLE
quadrant orientation

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#127]
If possible, label quadrants as follows:

upper right:  Q1
upper left:   Q2
lower left:  Q3
lower right: Q4

**Comment by LinearZoetrope** [comment]
Come to think of it, the quadrants have no meaning so it's trivial to just pretend this is what they are even if they don't correspond to the action number.

**Comment by jedirv** [comment]
As long as the quadrant orientation is consistent and the action names correspond to the correct one at that DP, then we're good. (as per https://github.com/SCAII/SCAII/issues/126)

**Comment by LinearZoetrope** [comment]
Finished
