### ISSUE TITLE
agent tank doesn't move during stepping forward sometimes

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#128]
seen on q-and-a branch

Can defer if provide at least two replays where this does not occur.  (one for tutorial and one for q&a for sandboxing)

**Comment by LinearZoetrope** [comment]
I'll probably just find replays where it doesn't happen. I looked into it
last night and it wasn't anything obvious. I have suspicions about the
cause but it will take a while to confirm them.

**Comment by LinearZoetrope** [comment]
Closing for now, I generated a new replay batch and none exhibit this behavior, leading me to believe this was due to a version mismatch or related weirdness.
