### ISSUE TITLE
Record games in core

### ISSUE THREAD

**Issue by LinearZoetrope** [SCAII/SCAII#17]
We'd like to have the core engine be able to record games.

For now, I think the best way of doing this is to explicitly have the glue for each language multiplex an outgoing action message to both the replay mechanism and the backend. Every so many actions it will explicitly ask both the backend and agent for serialization info.

The Replay mechanism also may need to be informed of configuration options such as configuration files the backend is loading, or models the agent is loading. This would all be taken care of in a header before the recording starts. After that, keyframes can be smaller since we can assume those configurations from the header are "fossilized" after the game starts.

The configuration would look something like:
> Which modules to serialize?
> Keyframe interval (how often to serialize)

The header for a Replay would look like:
> Agent to load and what type (RPC, Rust, etc)
> Backend to load and what type (etc)
> Configurations for both of these (action and state format, model paths, etc)

Followed by actions

I recommend a replay look something like

```rust
enum Action {
     DecisionPoint(protos::Action),
     Step,
}

enum ReplayAction {
    Header(ReplayHeader),
    Delta(Action),
    Keyframe(SerializationInfo,Action),
}

struct Replay {
    recording: Vec<ReplayAction>
}
```

Also

```
message BackendConfig {
    /* existing fields ... */
    // controls whether the backend automatically
    // goes to decision points with no input,
    // turn this off in replay.
    optional bool auto_step [default: true];
}

// Sent from backend to recorder each frame to denote a new
// step in the recording
message RecorderStep {
     optional Action action = 1;
     required bool is_decision_point = 2;
}
```

This can be used with [serde](https://serde.rs/) and a BufWriter to save it to and load it from `.scaii_replay` files.

The `Keyframe` struct should include the state and the action taken AFTER that state, not the action that leads to it. (Though I'm open to arguments otherwise).

**Comment by jedirv** [comment]
Question 1. For this enum value:     Keyframe(SerializationInfo,ActionPacket)

My understanding is that the info needed in SerializationInfo would be the same as the info that comes back to Recorder in this message:

message SerializationResponse {
	required bytes serialized = 1;
	required SerializationFormat format = 2;
}

... and then I wondered if that was the case, if we could just use it directly:  Keyframe(SerializationResponse,ActionPacket)

Would that work, or is there additional info you envision needing to be stored?

Question 2 - Assuming that it does work, was your thought that at replay time, that Replay would re-instantiate 

struct Replay {
    recording: Vec<ReplayAction>
}

from the persisted file, and then send one of these proto messages as appropriate for each ReplayAction?:

1. Action ScaiiPacket - containing what was captured in ReplayAction.Action(ActionPacket) or the ActionPacket part of Keyframe

2. SerializationInfo SciaiiPacket - i.e. the SerializationInfo from ReplayAction.Keyframe

3. an as yet unspecified ScaiiPacket to contain the info in ReplayAction.Header(ReplayHeader)

**Comment by LinearZoetrope** [comment]
Yeah, you can store the `SerializationResponse`(s), but you may also want some metadata specifying which module it came from. And the Header is something local to the replay, it would consist of a list of configuration commands.

**Comment by jedirv** [comment]
@LinearZoetrope update this (from Zoe at Jed's computer)

**Comment by jedirv** [comment]
ready for RTS integration.  Passing to Zoe.
