### ISSUE TITLE
Nail down an environment file descriptor

### ISSUE THREAD

**Issue by LinearZoetrope** [SCAII/SCAII#21]
For the tool #19 to work we need some manifest hinting where to put things for various environments. We need to nail down a file format for this. I'd recommend requiring an environment to have a `Scaii.toml` in its root that has things like:

```
[backend]
name = "foo"
language = "rust"

# what's supported
ffi = true
# RPC implies it has an executable that can run as a server
rpc = true

[wrappers]
python = true
```

**Comment by jedirv** [comment]
Jed note - for RTS we want a description file that can be parsed - what is the metadata for the backend

**Comment by LinearZoetrope** [comment]
Irrelevant
