### ISSUE TITLE
entityID disambiguation at Viz

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#32]
Reading through the documented protobuf definitions, I see that entityIDs are specific to certain endpoints.  Do we expect that more than one endpoint might be driving entity content into the UI during a single session?  If so, I'll need to tweak the way I handle entity state.  Currently I use the string form of the incoming id as a lookup key to find the master entity that corresponds, so I would need to augment that key to be something like <endpointID>.<entityID>

My current understanding is that Entities are strictly for representing game state and not for UI controls, etc.  If this is accurate, is there a use case where there would be more than one endpoint driving game state?

**Comment by Jragonmiris** [comment]
The idea was that agents might want to render viz stuff (such as overlays on the map), so it should probably be supported, but there may be an alternate better ways to handle this. Let's put this "on hold" and disregard that part of the comments until #27 is a bit clearer.

**Comment by jedirv** [comment]
Will only have single agent running things so no ambiguity
