### ISSUE TITLE
Triangle base len seems slightly wrong

### ISSUE THREAD

**Issue by LinearZoetrope** [SCAII/SCAII#42]
![image](https://user-images.githubusercontent.com/3078382/32073782-094b39b4-ba4c-11e7-8a83-1a1a60823e86.png)

I'm getting this with a baselen of 10 and a rectangle width of 10, these should be the same length. This is pretty minor, just thought I'd point it out.

**Comment by jedirv** [comment]
looks like I have some bogus bounds in play in the rectangle - probably a debugging tactic I forgot to remove.

**Comment by jedirv** [comment]
I found a few inconsistencies that I fixed in addition to this with the latest pull request.
