### ISSUE TITLE
viz should honor heading orientation of shapes

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#44]

**Comment by LinearZoetrope** [comment]
@jedirv Before you work on this, do we want heading to be in angles (0-360) or radians (0-2pi)? Internally I use 0-2pi but I don't know what Javascript prefers.

**Comment by jedirv** [comment]
The trig functions I used wanted radians.I tend to think in degrees but easy enough to convert.  How about we stick with radians and I convert when needed.

**Comment by jedirv** [comment]
I've implemented this on a new branch called orientation (not yet pushed) that I created off of my replay branch (which had rebased against dev prior).  One detail is that the way java script handles the sign of things is that as the radians increase in a positive direction, the axis rotates clockwise.  So, you may need to adjust the sign before forwarding depending on backend assumptions.  Ready for integration with RTS once I push the branch and do a pull request.  Then I'll assign to you for closing once you test it out with RTS.
