### ISSUE TITLE
Viz needs to accept close message from the system

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#45]
I had this note written down in my XAI notes file as a todo:  
___send close message to viz - stop listening

Should the stop listening command also stop the browser process?

**Comment by LinearZoetrope** [comment]
No, I don't think that's a good idea. The user may want to keep the window open for some reason. If it does anything, it should make it start listening again.

**Comment by jedirv** [comment]
To clarify this a bit more...

..for the use case where the user is doing a replay, navigating around, interacting with explanations, etc.  which component would emit the stop listening message and why would do so?  It seems to me the user will be running the show in that they might make it to the end of the game and then decide to hop back and review stuff again.  Is "stop listening" == "end of game reached" so we can reflect that in the UI?  Or is there a different use case where it applies?

**Comment by LinearZoetrope** [comment]
Yeah, we'll probably need to communicate "end of game", but I don't think closing the window is what we want. "Close" is already handled by closing the socket. Though we probably want to stop clearing the screen and popping up a dialogue and instead go back to trying for connections.

**Comment by jedirv** [comment]
resolved by communicating # steps in the replay, and vizInit resets everything.
