### ISSUE TITLE
VizInit message should configure game screen

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#47]
When starting up a replay, the VizInit message sent from Replay needs to convey the following info to the UI, so it can paint the screen:

- the dimensions of the game window (width, height)
- the length of the timeline (number of steps in game)
- information about the decision/explanation points that can be navigated to. (We should support configurability of explanations - we start with a pie chart approach, but in the future the UI might need to be different.  I think this information should flow at explanation time, rather than uI startup time, though, so this initial info would just need to be about the existence of a decision point, and its position on the timeline)

An implication is that the recorder needs to store all this info or, more likely, store the location of where replay can go find it (the directory into which the explanation info has stored)

Here's an initial syntax proposal for expanding VizInit:
```
message VizInit {
	optional bool test_mode = 1;
        optional i32 step_count = 2;
        optional i32 gameboard_width = 3;
        optional i32 gameboard_height = 4;
        repeated ExplanationPoint explanations = 5;
}
message ExplanationPoint {
        optional i32 step = 1;
        optional i32 sequence_num = 2; // the nth in the series of explanations
        optional string title = 3;  // short identifier to be shown on timeline (ex "knight attacks x")
        optional string description = 4;  // longer string that could be shown in tooltip on mouseover  (if the particular explanation system in play can generate a meaningful summary)
}
```

assigning to Zoe for review - assign back to Jed for implementation

**Comment by jedirv** [comment]
Do we also want the VizInit message to convey a key that explains what each shape represents?

**Comment by LinearZoetrope** [comment]
I think we can save the key for sprites.

**Comment by jedirv** [comment]
Considering renaming the "sequence_num" field of ExplanationPoint to "id".  It will still be a one-up sequence number, but coding-wise, I think the use context will always be as an id, perhaps to find it in a map.  Positioning in the UI will be managed using the step field.  Then we'd have:

message VizInit {
	optional bool test_mode = 1;
        optional i32 step_count = 2;
        optional i32 gameboard_width = 3;
        optional i32 gameboard_height = 4;
        repeated ExplanationPoint explanations = 5;
}
message ExplanationPoint {
        optional i32 step = 1;
        optional i32 id = 2; // the nth in the series of explanations
        optional string title = 3;  // short identifier to be shown on timeline (ex "knight attacks x")
        optional string description = 4;  // longer string that could be shown in tooltip on mouseover  (if the particular explanation system in play can generate a meaningful summary)
}

**Comment by jedirv** [comment]
Not relevant.   Closing.
