### ISSUE TITLE
expand UserCommandType to support navigation, etc

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#48]
UserCommandType currently has NONE and EXPLAIN. I propose adding:

```
message UserCommand {
	enum UserCommandType {
		NONE = 0;
		EXPLAIN = 1;
                NAVIGATE = 2;  // hop to particular point in game
                QUIT_REPLAY = 3;
                SELECT_REPLAY = 4; // for when we expose existing replays in the UI
                SET_REPLAY_SPEED = 5;
                PLAY_GAME_SEGMENT = 6; // conveying the bounds of where to start and stop playing for an explanation
                LOOP_GAME_SEGMENT = 7; // if the user selects loop, the game segment will keep repeating
                PAUSE_REPLAY = 8;
                UNPAUSE_REPLAY = 9;
	}
	required UserCommandType command_type = 1;
	repeated string args = 2;
}
```
As it is now, we have Command Types and a vector of arguments.  Upsides of this approach:
- command arguments can be tinkered with without needing to regen the protobufs
- protobuf definition files don't have to take on all the complexity of having a structure for each command variant
Downside:
- command formats are not compile checked

Zoe, how do you feel about this? My thought is that since the commands mostly only need to be known by the two endpoints (replay and viz) that this looser list-of-args approach is fine.

Pass back to Jed for implementation

**Comment by LinearZoetrope** [comment]
I personally like compile-time checks, but yeah it's getting a bit onerous having such nested commands.

This seems good, but I'd caution that we should maybe put some of them like setting the speed or looping on hold until everything is running.

**Comment by jedirv** [comment]
So far we've implemented the critical ones:

message UserCommand {
	enum UserCommandType {
		NONE = 0;
		EXPLAIN = 1;
		PAUSE = 2;
		RESUME = 3;
		REWIND = 4;
		POLL_FOR_COMMANDS= 5;
		JUMP_TO_STEP = 6;
		JUMP_COMPLETED = 7;
		SET_SPEED = 8;
	}
	required UserCommandType command_type = 1;
	repeated string args = 2;
}

... leaving the following:.  
 
QUIT_REPLAY  - this would allow the Replay system to shutdown gracefully  but as it is now, if the UI is closed, the system panics and closes so not sure if this is important enough to keep in play

SELECT_REPLAY - once multiple replay files exist we could support switching between them,or we could just have the user restart the system aimed at a new file - good enough for research?


PLAY_GAME_SEGMENT 
LOOP_GAME_SEGMENT 
       These two made an assumption about where the explanation thinking would go.  Thinking we can hold off on these unless they come up in the UI plan.

I'm wondering if we should close this issue and move the QUIT and SELECT to other issues, or even to an external list of deferred items.  We can discuss at meeting time.
