### ISSUE TITLE
load the real RTS if it is built and in play

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#56]
How best to make the loading of the real RTS smooth...

Here are some options - 
A.  look to see if target/debug/backend.dll exists in an assumed location, (assume that sky-rts is cloned into the same dir as SCAII).  If that file exists, it will load it using the correct InitAs message.
B. require passing an argument into replay that is the path to the dll - a more generic approach if we have other backends in the future.

I also realize now I'll have to do some refactoring in either case to allow the tests and "live" mode to coexist.  

I'm leaning toward B. Thoughts, Zoe?  (assigning to Zoe for review)

**Comment by jedirv** [comment]
Reconsidering - perhaps the best is to by default try to load the RTS in the assumed location unless a command line arg is provided that overrides that.

**Comment by jedirv** [comment]
look for rts in 
move target/release/backend.dll to $HOME/.scaii/backends/bin/sky_rts.dll

**Comment by LinearZoetrope** [comment]
Done/RTS is static dispatch now anyway
