### ISSUE TITLE
default values replace "undefined" 

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#6]
in the section called "Optional Fields And Default Values" on this page...

https://developers.google.com/protocol-buffers/docs/proto

... it states that " When a message is parsed, if it does not contain an optional element, the corresponding field in the parsed object is set to the default value for that field."  I'm seeing this happen in the tester where a value for x in a Pos field is presumably not present, and thus undefined, but changed to a default when accessed. Here's a copy of the data state in javascript...

updatePos: proto.scaii.common.Pos
    array: (2) [undefined × 1, 79.87378692626953]  <<<<REF A
    .
    .
    .
    x:0           <<<<REF B
    y:79.87378692626953

...at REF A,the content of the Pos field for the updating entity has x being undefined (i.e. not preset). I had assumed that calling getX() on that Pos object would return the javascript value "undefined",but it converts it to the default for a numeric which is 0.0 , so this x value of 0.0 (REF B) looks like a real value that I have to apply which is not what we want as I understand.

Maybe we discussed this already and there's a way to circumvent, like going around the accessor method and accessing data directly, but that feels a tad brittle.  Thoughts?

**Comment by Jragonmiris** [comment]
I don't know the exact library in Javascript, but in most languages an `optional` field will have a "hasX"/"has_x" method, like hasPos or hasX. You need to call that BEFORE you call getPos or getX.

**Comment by jedirv** [comment]
Got it.

Jed
