### ISSUE TITLE
Entity State Awareness

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#88]
For work on this , I've created a branch called entity_info. I've made the changes to protobufs there and will push the new generated files next, and rust-side changes.

**Comment by jedirv** [comment]
sending false values across 

	map<string,bool> boolMetadata = 5;

yield value of undefined on the javascript side, so I worked around it by adding the following to carry string values of "true" and "false":

	map<string,string> boolStringMetadata = 9;

**Comment by jedirv** [comment]
One past the assertion failure for undefined false values, found that hp and other info just sent at beginning of game or when I do a jump.  This yields two issues:


First, need Zoe to add state transmission to render_delta(...) - didn't want to assume the logic would be the same.

Second, when I jumped on the timeline, and print out the hp values being sent from the backend, it looks like (perhaps) the entity ids are not continuous across the jump events, as I get an effect where the hp assignments are suddenly switched.  In the following case, I was on step 1 and jumped to step 2:


(C:\Program Files\Anaconda3) C:\Users\Jedi\.scaii\git\SCAII\core>cargo run file
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   C:\Users\Jedi\.scaii\git\SCAII\core\Cargo.toml
workspace: C:\Users\Jedi\.scaii\git\SCAII\Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   C:\Users\Jedi\.scaii\git\SCAII\backends\sky-rts\Cargo.toml
workspace: C:\Users\Jedi\.scaii\git\SCAII\Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `C:\Users\Jedi\.scaii\git\SCAII\target\debug\replay.exe file`
Running Replay in live mode...
Name: aReplay_contrastive_0413.scr
Name: replay.scr
Name: replayMagesh0411.scr
Name: replayNotSureWhich.scr
Name: replay_contrastive_eb_0.scr
Name: replay_contrastive_eb_1.scr
Name: replay_eb0_0413.scr
Name: replay_eb_0.scr
Name: replay_eb_1.scr
Name: replay_friday1_51.scr
Name: replay_hasSpawnsError.scr
Name: x0411saliencyFix.scr
Name: xreplay_0413.scr
================RECEIVED UserCommandType::SelectFile================
load file aReplay_contrastive_0413.scr!
replay_actions this long after header removed 10
....get_keyframe_indices saw keyframe
....get_keyframe_indices saw keyframe
....get_keyframe_indices saw delta
....get_keyframe_indices saw delta
....get_keyframe_indices saw delta
....get_keyframe_indices saw delta
....get_keyframe_indices saw keyframe
....get_keyframe_indices saw delta
....get_keyframe_indices saw delta
....get_keyframe_indices saw delta
 mode_transition_index will be 2
keyframe_indices : [0, 2, 7]
Explanation?  YES
MAPPING EXPL POINTS recieved this many 1
is_empty()? FOUND SOME:1
sequence length is 11
len is 11
...adding expl info to config message...
......step_index 1 titleAttack top_left
rts got Cfg
executing first run step to get game board shown
next returns pkt at index 0
Rendering
entity : Entity(0, Generation(1)) HitPoints : 100
Rendering
entity : Entity(1, Generation(1)) HitPoints : 100
Rendering
entity : Entity(2, Generation(1)) HitPoints : 10
Rendering
entity : Entity(3, Generation(1)) HitPoints : 100
Rendering
entity : Entity(4, Generation(1)) HitPoints : 10
================RECEIVED UserCommandType::JumpToStep================
args : ["2"]
finding keyframe index prior to 2
-look backward through the list of keframe indices starting at 3
position in keyframe index list is 2
index of keyframe listed here is 7
position in keyframe index list is 1
index of keyframe listed here is 2
determined that 2 is the index prior to 2
prior_keyframe_index : 2
PacketRetrievalModeForJump is PrependKeyframeMode
   ...pushed keyframe at index 2
   ...replay_sequencer pushed action at index 2
   ...incr index to 3 (after push)
   ...replay_sequencer.index is now 3
Entity(0, Generation(1))
Entity(1, Generation(1))
Entity(2, Generation(1))
Entity(3, Generation(1))
Entity(4, Generation(1))
Rendering
entity : Entity(0, Generation(2)) HitPoints : 100
Rendering
entity : Entity(1, Generation(2)) HitPoints : 10
Rendering
entity : Entity(2, Generation(2)) HitPoints : 100
Rendering
entity : Entity(3, Generation(2)) HitPoints : 10
Rendering
entity : Entity(4, Generation(2)) HitPoints : 100
Action caused rts.update()


If it's true that the id assignments can shift across jumps, it means we can not safely demo both jumping around and exposed hit points at the same time.

I pushed on the entity_info branch for Zoe to replicate (I used file replay_contrastive_0413.scr)

**Comment by LinearZoetrope** [comment]
1 -- My intention was to assume metadata values are constant between deltas, is that not good enough?
2 -- This should be soft-fixed by the fact that on a jump the RTS sends the entire state.

**Comment by jedirv** [comment]
re 1) Oh weird, I totally missed the hipoints being sent in the render_delta.  I didn't see that delta value arrive at the UI yet, though as there is another assertion fail right at that point (I think) that I haven't isolated yet.  No problems there, I just have to treat the metadata the same as other info like position and imbed it in the current global state object that I'm keeping.  Should have done that from the get go, 

re 2).  I'll attach two screen shots - first one is the hitpoints of three of the entities at step one, then without changing anything else, I jump to step two by clicking on the nav bar and suddenly the hit points are moved around, leading me to think that the entity ids have been randomly reassigned at the reset caused by the nav jump (which sends an emit_viz pkt to the backend followed by the keyframe + actions sequence).  Do you think this validates my concern or is this a different bug perhaps?

(actually after I attached them I see they are in reverse order with step two showing first) 

![hitpointsafterjumptostep2](https://user-images.githubusercontent.com/1120103/39413993-fcaf3fd4-4be6-11e8-824e-9044efde68cc.jpg)
![hitpointsstep1](https://user-images.githubusercontent.com/1120103/39413994-fccb9c24-4be6-11e8-9b1e-650f81010721.jpg)

**Comment by jedirv** [comment]
Oh, frig.  When I get Hitpoints sent as 0 like this:

            float_metadata.insert("Hitpoints".to_string(), 0 as f32);

... or like when the hp actually does hit zero, the deser on the javascript side fails on an assert as the value comes in as undefined - for pre-demo  expediency I'll do the same workaround where I'll send the float value as a string and then convert it back to a number on the js side.,  Then we can troubleshoot that after the demo.  

Stepping through the code, it looks like the the value data is missing so it might be a rust side bug.  I think the fact that a zero or false value is problematic probably means a language related conversion or oversight is in play.  I'm quitting for the night and will pick up in morning.

**Comment by LinearZoetrope** [comment]
There is something we can try, but it will require a little co-operation.

**Comment by jedirv** [comment]
Good news - I wove metadata into my delta handling and problem 2 seems to have gone away. I'll do some more testing but it looks like the id assignments aren't changing and it was a side effect of a bug on my end. I'll test some more and close if cannot replicate.

**Comment by jedirv** [comment]
cannot replicate!
