### ISSUE TITLE
complaint after 12th packet - empty entity

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#9]
I'm getting farther now but hit the error below after I send the 12th state message back.  The complaint is about entity id 0 , which appears to be completely empty.  On my side, I log the outbound entity with id 0 as having both a pos and a shape :

```
scaiiViz.js:440 ++++++++++++++ENTITY SEND 0++++++++++++++++
scaiiViz.js:84 - - - - - - - - - - -
scaiiViz.js:85 entity 0
scaiiViz.js:86 - - - - - - - - - - -
scaiiViz.js:89 position: x: 91.37215423583984 ; y: 98.0229721069336 ;  ; delete?: false
scaiiViz.js:92 shape count 1
logUtils.js:153 - - - - - - - - - -
logUtils.js:154     shape: 0
logUtils.js:155 relative position: x: 0 ; y: 0 ; 
logUtils.js:156 R: 164; G: 19; B: 91; A: 212; 
logUtils.js:157 Rect missing
logUtils.js:158 Tri  baseLen: 4.517421722412109
logUtils.js:159 delete: false
logUtils.js:160 - - - - - - - - - -
```
Perhaps pulling an empty entity into play inadvertently on the backend somehow?  I can't think of a way that on the 12th iteration the minimal code I have between where I log and send could be causing that kind of issue.

```
Sending a VizInit message
Protocol: We'll send you a ScaiiPacket delta, you apply it and send us your entity info (one ScaiiPacket in a MultiMessage).
Connection will be closed after a random number of ticks between 10 and 20, or with anerror message on desynchronization or incorrect response.
Sending a VizInit ScaiiPacket, no response expected
Sending first volley of entities to initialize list
thread 'main' panicked at 'Error decoding entities, expected FULL data: Entity lacks pos field. (Note: got Entity { id: 0, pos: None, shapes: [], delete: false })', src\main.rs:229:20
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:379
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   4: std::panicking::begin_panic_new<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:553
   5: rpc_viz::verify_scaii_packet::{{closure}}
             at .\src\main.rs:229
   6: core::ops::function::impls::{{impl}}::call_once<(&scaii_defs::protos::Entity),closure>
             at C:\projects\rust\src\libcore\ops\function.rs:191
   7: core::option::Option<&scaii_defs::protos::Entity>::map<&scaii_defs::protos::Entity,rpc_viz::entity::IdEntity,&mut closure>
             at C:\projects\rust\src\libcore\option.rs:398
   8: core::iter::{{impl}}::next<rpc_viz::entity::IdEntity,core::slice::Iter<scaii_defs::protos::Entity>,closure>
             at C:\projects\rust\src\libcore\iter\mod.rs:1073
   9: alloc::vec::{{impl}}::spec_extend<rpc_viz::entity::IdEntity,core::iter::Map<core::slice::Iter<scaii_defs::protos::Entity>, closure>>
             at C:\projects\rust\src\liballoc\vec.rs:1825
  10: alloc::vec::{{impl}}::from_iter<rpc_viz::entity::IdEntity,core::iter::Map<core::slice::Iter<scaii_defs::protos::Entity>, closure>>
             at C:\projects\rust\src\liballoc\vec.rs:1808
  11: alloc::vec::{{impl}}::from_iter<rpc_viz::entity::IdEntity,core::iter::Map<core::slice::Iter<scaii_defs::protos::Entity>, closure>>
             at C:\projects\rust\src\liballoc\vec.rs:1695
  12: core::iter::iterator::Iterator::collect<core::iter::Map<core::slice::Iter<scaii_defs::protos::Entity>, closure>,alloc::vec::Vec<rpc_viz::entity::IdEntity>>
             at C:\projects\rust\src\libcore\iter\iterator.rs:1303
  13: rpc_viz::verify_scaii_packet
             at .\src\main.rs:217
  14: rpc_viz::test_loop<rand::XorShiftRng>
             at .\src\main.rs:475
  15: rpc_viz::test_viz_client
             at .\src\main.rs:497
  16: rpc_viz::main
             at .\src\main.rs:502
  17: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  18: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  19: main
  20: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  21: BaseThreadInitThunk
error: process didn't exit successfully: `C:\Users\Jed Irvine\exact\SCAII\target\debug\rpc-viz.exe configuration.toml` (exit code: 101)
```

**Comment by Jragonmiris** [comment]
I don't see how this could happen on the backend, the only time that error message happens is when decoding an entity from bytes in a packet you send. That function doesn't even have **access** to the backend's entity map.

**Comment by Jragonmiris** [comment]
Yeah, on my end all it's doing is directly iterating over the decoded version of the packet you sent and calling a function to attempt to turn the packet into one of my non-nullable entities. By that point in the code it doesn't even touch the backend entities.

**Comment by jedirv** [comment]
I spent about 90 minutes trying to configure some tooling to intercept and decode the "on-the-wire" protobuf packet without success (to see what's actually flowing).  I tried using wireshark, but it can't sniff on localhost loop connections.  I then found RawCap, a tool which will capture that and create a file that wireshark can read. I successfully (I think) captured the exchange and loaded it in wireshark , andcan see the rawbytes.  I couldn't manage to decode them from protobuf into something readable, however. 

I found a project on github :  https://github.com/128technology/protobuf_dissector, which is a wireshark plugin designed to do protobuf decoding, but its a few years since thelast commit.  I followed instructions for using it (positioning it under wireshark's plugin dir, positioning a copy of our .proto file) but it gave error complaints when trying to load the plugin, which is a lua file.  Two of the lua method calls used the value base.HEX and the error message said that only one from a set of other  values was allowed there.  I changed it to one of those and the error message disappeared.  But, following the further instructions did not seem to match what I was seeing - I think wireshark has evolved in the meantime.  One of the confusing things is that it seemed to be only configured to allow decoding protobuf packets if they are in UDP packets - in wireshark, it says they are tcp.  

So far, then, I don't have a way to "tap the wire" to prove where the issue is.  There is a prefs.lua file that deals with UDP port configuration.  With your lua skills its possible that you might be able to figure out how to get it to work, unless we find another route around the problem.  Or, perhaps you may have an intuition on using a different one of the "allowed" parameters in the lua file. They were : base.NONE, base.DOT, base.DASH, base.COLON, base.SPACE.  It was instead of base.HEX in this call:

value    = ProtoField.bytes ("protobuf.value", "Value", base.HEX, nil, nil, "Field value bytes"),

I'm sure you'd need to see more of the code to make sense of it, but thought I'd put it out there in case.  I'm out of time to work on it today.

**Comment by Jragonmiris** [comment]
Idea: you're probably not sending entity zero, you're accidentally pushing a dead entity. Since ID is a required field, 0 is the default value. That entity is consistent with the "zero entity" so to speak -- ID of 0 and nothing set.

**Comment by Jragonmiris** [comment]
Can you push the viz code to remote at some point so I can poke at it?

**Comment by jedirv** [comment]
You are correct. Since I was fooled by the id=0, I wasn't looking further down and seeing  that I was pushing an undefined entity.  That undefined entity was there because I wasn't doing the correct javascript delete maneuver for the entity delete event.  It gets past this error now, so I'll close.
