### ISSUE TITLE
missing tower problem

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#90]
Here' show it unfolds...

1. the tower is killed
2. that tower's entity arrives at the ui with delete==true
3. my UI code removes the id of that tower from the "master entity list"
4. (step is missing)
5. next entity that comes in is the first move of the next epoch which only includes the agent entity

missing step is an entity coming in to re-instantiate the revived tower.  Here we pay the price of being fancy with the deltas. I wonder if the simplest fix be to just always send all the state for now?

**Comment by LinearZoetrope** [comment]
I think I got this @jedirv test on your end?

**Comment by LinearZoetrope** [comment]
@jedirv It appears to be working mostly, However, there still seems to be a small bug about clicking on or very near decision points where the state doesn't change. If you check out the new trained.scr, the state is just utterly borked if you click the second decision point.

**Comment by LinearZoetrope** [comment]
That replay is dead new, but I may have fixed it. Will see once more replays are generated.

**Comment by jedirv** [comment]
Behavior looks good to me, and a bit of debugging on js side reveals the right stuff is happening.
