### ISSUE TITLE
negative hitpoints issue isolated

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#92]
So I am getting negative hit points from the backend, and it happens after a hop - which reset the backend with a keyframe.  When I let the game play for example,agent hp is 35 and stays that way for a while.  During the same stretch if I hp into it, I see -6.4.

To replicate, full_train_constrastive, click on step 49 or thereabouts.

**Comment by LinearZoetrope** [comment]
Figured it out, I'm an idiot. I was a lua problem. I was setting the HP of the killing unit (from the Lua perspective) to the HP of the dead unit, so on respawn it was causing the agent HP to be reset to a negative value.

**Comment by LinearZoetrope** [comment]
(Note: this fix makes all current replays invalid).
