### ISSUE TITLE
showing hit points as %-of-bar

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#93]
Lacking gaming experience need to ask...

If I show hit points as a percent of bar filled rather than text, what is the max value of each bar? Would it be according to unit type?

**Comment by LinearZoetrope** [comment]
I need to send that.

**Comment by jedirv** [comment]
Oh, right - maybe make that part of the same protobuf change to reduce churn?

**Comment by LinearZoetrope** [comment]
Nah, it's just gonna be max_hp in the metadata

**Comment by LinearZoetrope** [comment]
or Max Hp? Either or.

**Comment by LinearZoetrope** [comment]
Fixed

**Comment by LinearZoetrope** [comment]
As Max Hp
